// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb_mwPvB8tlqftEfSL-fdDg5ug8QO0huE',
    appId: '1:889775322897:web:c988caa6ee681349747eb0',
    messagingSenderId: '889775322897',
    projectId: 'verdantoff-929f7',
    authDomain: 'verdantoff-929f7.firebaseapp.com',
    storageBucket: 'verdantoff-929f7.firebasestorage.app',
    measurementId: 'G-D7FYKWL9CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEw0FIjF0ipeiC8LbrgsMR4P3HTv3tZaM',
    appId: '1:889775322897:android:319373e074dc924f747eb0',
    messagingSenderId: '889775322897',
    projectId: 'verdantoff-929f7',
    storageBucket: 'verdantoff-929f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHBTP08vutA75QiVQlux1hFLFp-SlK_QE',
    appId: '1:889775322897:ios:341fc5560664d346747eb0',
    messagingSenderId: '889775322897',
    projectId: 'verdantoff-929f7',
    storageBucket: 'verdantoff-929f7.firebasestorage.app',
    iosBundleId: 'com.example.verdantoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHBTP08vutA75QiVQlux1hFLFp-SlK_QE',
    appId: '1:889775322897:ios:341fc5560664d346747eb0',
    messagingSenderId: '889775322897',
    projectId: 'verdantoff-929f7',
    storageBucket: 'verdantoff-929f7.firebasestorage.app',
    iosBundleId: 'com.example.verdantoff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb_mwPvB8tlqftEfSL-fdDg5ug8QO0huE',
    appId: '1:889775322897:web:9d3264cda54e1b9c747eb0',
    messagingSenderId: '889775322897',
    projectId: 'verdantoff-929f7',
    authDomain: 'verdantoff-929f7.firebaseapp.com',
    storageBucket: 'verdantoff-929f7.firebasestorage.app',
    measurementId: 'G-KQZ2KQZBMR',
  );
}
